name: rolling_together
description: This project is for google solution challenge 2023

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  cloud_firestore: ^4.3.2
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  flutter_screenutil: ^5.6.1
  image_picker: ^0.8.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

