// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMG5HKaTn-Fj7NGHudmhcJxf-nnaqTNWg',
    appId: '1:181332173172:web:35e0217ff63ff9a35f4c21',
    messagingSenderId: '181332173172',
    projectId: 'rollingtogether-9e9e2',
    authDomain: 'rollingtogether-9e9e2.firebaseapp.com',
    storageBucket: 'rollingtogether-9e9e2.appspot.com',
    measurementId: 'G-G2PK7T7G41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfuYPtbwnPkioFgcHw1D-utdjkzSHY9Xc',
    appId: '1:181332173172:android:be7e96f3d02ae9855f4c21',
    messagingSenderId: '181332173172',
    projectId: 'rollingtogether-9e9e2',
    storageBucket: 'rollingtogether-9e9e2.appspot.com',
  );
}
